### ISSUE TITLE
Still raising "NotLoggedException()"

### ISSUE THREAD

**Issue by lucas7bm** [PokemonGoF/PokemonGo-Bot#3800]
Well, I was using the bot on dev branch these days and it was working well.
Since yesterday, however, I simply can't connect into any account.
I've reinstalled and now I'm trying to make 'master' work. I'm having problems to login into my old google account, so now I'm trying to login into a PTC account that I've recently created.

Am I doing something incredibly wrong (and probably obvious) or is there some problem with new accounts?

P.S Yep, I tried everything that I've found here on "Issues" related to this problem, but nothing helped. :/

### Actual Behavior

2016-08-12 21:06:02,726 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 578, in <module>
    main()
  File "pokecli.py", line 145, in main
    report_summary(bot)
  File "pokecli.py", line 180, in report_summary
    metrics.capture_stats()
  File "/root/PokemonGo-Bot/pokemongo_bot/metrics.py", line 84, in capture_stats
    response_dict = request.call()
  File "/root/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/root/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
2016-08-12 21:06:02,737 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 44, in urlopen
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2016-08-12 21:06:02,738 [sentry.errors.uncaught] [ERROR] [u'NotLoggedInException', u'  File "pokecli.py", line 578, in <module>', u'  File "pokecli.py", line 145, in main', u'  File "pokecli.py", line 180, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 90, in call', u'  File "pokemongo_bot/api_wrapper.py", line 58, in can_call']
Sex Ago 12 21:06:02 BRT 2016 Pokebot configs/config.json Stopped.
Press any button or wait 20 seconds to continue.

### Your config.json (remove your credentials and any other private info)
```
{
    "auth_service": "ptc",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "encrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
      "any": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
```

### Other Information
OS: Linux Mint
Branch: master
Git Commit: c450b19a3e44cc660576940009da6e7c85a0121f
Python Version: Python 2.7.6

**Comment by lucas7bm** [comment]
(I can't edit my comment, for some reason)

Well, I discovered that in this my new account (PTC) I simpy can't use the bot.
I've tried with the bot installed on one of my friend's PC and the error is the same.
Can Niantic simply block new accounts from using the bot? Doesn't seem plausible to me, but.. idk.

**Comment by k4n30** [comment]
I'm going to leave this issue open as it'd the first time I've seen that error, but my guess is it's related to one of:

#3682 - META Server busy or offline issues
#3700 - META Soft bans - Try again spins / Pokemon vanishing
#3746 - META Banwaves - Permanent Bans

**Comment by jerFXD** [comment]
You might haven't verified your email?

**Comment by philly223** [comment]
Verifying your email should fix this issue as it will allow you to actually login to your account

**Comment by lucas7bm** [comment]
Since I can play with my another account (a Google one) I just opened this thread because maybe it can help.

About the previous comments and tips:
My email is verified, of course, and I can play normally in the phone. There is no SoftBan or server issue (as far as I can imagine).
I have never used bot in this account, so I imagine we can discard this possibility (any kind of ban).

**Comment by Luab** [comment]
I have the same issue. Using google account btw. Tried clean one, which fails too. Tried clean install. Nothing helps.

**Comment by k4n30** [comment]
@lucas7bm still an issue?

**Comment by lucas7bm** [comment]
@k4n30 Yep, the problem still persists.
I didn't receive the notification, so I took all this time to reply.

Here is a printscreen that I took right now.

![captura de tela de 2016-08-18 19 27 27](https://cloud.githubusercontent.com/assets/13841610/17792871/dcc5800c-6579-11e6-8640-015d28af6265.png)

**Comment by k4n30** [comment]
@lucas7bm no worries, if you havent already - can you update to the latest version and try again.

p.s Please don't screen shot error messages, text works better for us and other users searching for like issues

**Comment by lucas7bm** [comment]
@k4n30 Well, I'm using the latest master version.
I don't know why, but today I created a new PTC account, with another email, and the new one works well.
I really don't know what's going on, perhaps happened some server issue when I was creating the first PTC one, but that's just a blind guess. I'll keep trying, though.

**Comment by k4n30** [comment]
@lucas7bm so this can be closed?

**Comment by lucas7bm** [comment]
@k4n30 I guess so. Seems like a PTC account problem, the bot still works well.
I'm closing the topic. Thanks for everyone!
