### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte

### ISSUE THREAD

**Issue by davidspeijer** [PokemonGoF/PokemonGo-Bot#4718]
### Expected Behavior

Bot running.

### Actual Behavior

Error message, see traceback below.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/5X1ZKz2x

### Output when issue occurred

http://pastebin.com/M3xHmRmS

### Steps to Reproduce

Run the bot

### Other Information
OS: CentOS
 
Branch: latest dev
 
Git Commit: 9605728255f996f156fd00b1467d7f14afb1d3a4
 
Python Version: Python 2.7.5
 
Any other relevant files/configs (eg: path files)

**Comment by balpoint** [comment]
Getting the exact same error output.

**Comment by lwq008** [comment]
I hit into this and used VPN to resolve it. Looks like to me that my IP address was banned.

**Comment by balpoint** [comment]
nope with different IP still gtting this erro.r

**Comment by Billy2Kid** [comment]
same probleme

**Comment by HerrmannHinz** [comment]
same error. debian 8 box on google computing. 

`2016-08-25 14:04:07,100 [PokemonGoBot] [INFO] [login_started] Login procedure started.
Traceback (most recent call last):
  File "pokecli.py", line 705, in <module>
    main()
  File "pokecli.py", line 187, in main
    report_summary(bot)
  File "pokecli.py", line 221, in report_summary
    metrics.capture_stats()
  File "/opt/PokemonGo-Bot/pokemongo_bot/metrics.py", line 102, in capture_stats
    response_dict = request.call()
  File "/opt/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 239, in call
    result = self._call()
  File "/opt/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 163, in _call
    accelerometer_axes=3
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 533, in init
    setattr(self, field_name, field_value)
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 134, in CheckValue
    raise ValueError('Value out of range: %d' % proposed_value)
ValueError: Value out of range: -146
2016-08-25 14:04:09,729 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
  File "/opt/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-25 14:04:09,731 [sentry.errors.uncaught] [ERROR] [u'ValueError: Value out of range: -146', u'  File "pokecli.py", line 705, in <module>', u'  File "pokecli.py", line 187, in main', u'  File "pokecli.py", line 221, in report_summary', u'  File "pokemongo_bot/metrics.py", line 102, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 239, in call', u'  File "pokemongo_bot/api_wrapper.py", line 163, in _call', u'  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 533, in init', u'  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 669, in field_setter', u'  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 134, in CheckValue']
Thu Aug 25 14:04:09 UTC 2016 Pokebot  Stopped.`

**Comment by Baconnaise** [comment]
Same error on here. I fired up my VPN and changed IP's to no avail.

**Comment by davidspeijer** [comment]
Changing `"health_record": true`, to `"health_record": false`, took away some errors.

Now it is just:

`Traceback (most recent call last):
  File "pokecli.py", line 705, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.start()
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 109, in start
    init_inventory(self)
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1219, in init_inventory
    _inventory = Inventory(bot)
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1086, in __init__
    self.refresh()
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1096, in refresh
    self.update_web_inventory()
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1103, in update_web_inventory
    json_inventory = json.load(infile)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 6006 (char 6005)
`

Changing 
```
{ 
         "type": "UpdateWebInventory",
         "config": {
            "enabled": true
         }
      },
```
To 
`{ 
         "type": "UpdateWebInventory",
         "config": {
            "enabled": false
         }
      },
`
Doesnt change anything.

**Comment by sohje** [comment]
@davidspeijer Do you have this file web/inventory-botname.json? If so - whats inside? Can you try to clear it?

**Comment by r3pek** [comment]
@sohje I don't have it.... and yes, same error as OP

**Comment by sohje** [comment]
@r3pek could you please make file web/inventory-botname_here.json and try again?

**Comment by davidspeijer** [comment]
Clearing the file result in:

> Traceback (most recent call last):
  File "pokecli.py", line 705, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.start()
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 109, in start
    init_inventory(self)
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1219, in init_inventory
    _inventory = Inventory(bot)
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1086, in __init__
    self.refresh()
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1096, in refresh
    self.update_web_inventory()
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1103, in update_web_inventory
    json_inventory = json.load(infile)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by r3pek** [comment]
Nop... same problem. Either with empty file or with empty JSON

`2016-08-25 15:54:04,825 [PokemonGoBot] [INFO] 
Traceback (most recent call last):
  File "pokecli.py", line 705, in <module>
    main()
  File "pokecli.py", line 187, in main
    report_summary(bot)
  File "pokecli.py", line 221, in report_summary
    metrics.capture_stats()
  File "/root/PokemonGo-Bot/pokemongo_bot/metrics.py", line 102, in capture_stats
    response_dict = request.call()
  File "/root/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 239, in call
    result = self._call()
  File "/root/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 188, in _call
    return PGoApiRequest.call(self, signature)
TypeError: call() takes exactly 1 argument (2 given)
2016-08-25 15:54:04,905 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-25 15:54:04,913 [sentry.errors.uncaught] [ERROR] [u'TypeError: call() takes exactly 1 argument (2 given)', u'  File "pokecli.py", line 705, in <module>', u'  File "pokecli.py", line 187, in main', u'  File "pokecli.py", line 221, in report_summary', u'  File "pokemongo_bot/metrics.py", line 102, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 239, in call', u'  File "pokemongo_bot/api_wrapper.py", line 188, in _call']
`

**Comment by davidspeijer** [comment]
Removing resulting in

> Traceback (most recent call last):
  File "pokecli.py", line 705, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.start()
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 109, in start
    init_inventory(self)
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1219, in init_inventory
    _inventory = Inventory(bot)
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1086, in __init__
    self.refresh()
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1096, in refresh
    self.update_web_inventory()
  File "/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1102, in update_web_inventory
    with open(web_inventory, "r") as infile:
IOError: [Errno 2] No such file or directory: u'/PokemonGo-Bot/pokemongo_bot/../web/inventory-***.json'

**Comment by sohje** [comment]
@davidspeijer @r3pek  Could you put this into file?
```js
[]
```
or 
```js
{}
```

**Comment by r3pek** [comment]
@sohje same problem...

**Comment by davidspeijer** [comment]
@sohje {} solved it for me... :)

**Comment by sohje** [comment]
@davidspeijer good ;]

**Comment by r3pek** [comment]
@davidspeijer changed anything else besides adding {} to the file?

**Comment by davidspeijer** [comment]
No, my original config is now working without any problems :).

**Comment by r3pek** [comment]
thx.... I open to ideas then ;) this is a fresh install...

**Comment by r3pek** [comment]
OK, mine is fixed too... pgoapi was too old ;)

**Comment by r3pek** [comment]
just an update, occasionally i still get this error.... so, it's not  completely solved

**Comment by Gobberwart** [comment]
I've put in a PR to fix this (create a "default" inventory file if it doesn't already exist). Hopefully that will resolve it.

@r3pek This specific error should only occur if the inventory file doesn't exist. When you say it "occasionally" still happens, is it exactly the same or something different? I'd like to know so I can track/fix any other bugs.

**Comment by r3pek** [comment]
This is what i have at start now (can't start it again, even with "empty" inventory)
http://pastebin.com/yLpVuvA7

**Comment by Gobberwart** [comment]
@r3pek create inventory file just with [] at the top (nothing else) and restart. Does that work?

**Comment by r3pek** [comment]
@Gobberwart no. same error. with {} or []

**Comment by r3pek** [comment]
Same error as Issue #4380. Just at another place

**Comment by Gobberwart** [comment]
@r3pek looks like your error is different and not related to inventory json file.

**Comment by r3pek** [comment]
yeah.... same error message though :(

**Comment by Gobberwart** [comment]
@r3pek I assume you've tried updating requirements? This looks like pgoapi error which might be solved by updating.

Try: pip install -r requirements.txt --upgrade

**Comment by r3pek** [comment]
Nothing to upgrade. Same problem.

**Comment by Gobberwart** [comment]
Please paste your most recent output/error

**Comment by r3pek** [comment]
It's the one on the pastebin. Nothing changed.

**Comment by Gobberwart** [comment]
Hmmm have you got the latest build?

**Comment by r3pek** [comment]
Yes... Running dev branch.

**Comment by hobbes3** [comment]
Latest commit 3622c032257887e5898778635c7382017879dafe fixes the problem for me.

**Comment by r3pek** [comment]
commit 09403f5 also works

**Comment by mjmadsen** [comment]
Since the original poster's issue is resolved, I am closing.

**Comment by castorfou** [comment]
I have ths issues since last update this morning.
When calling for  Most Perfect Pokemon, when starting Bot.

`[2016-08-30 10:46:20] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 768, in <module>
    main()
  File "pokecli.py", line 119, in main
    bot = start_bot(bot,config)
  File "pokecli.py", line 86, in start_bot
    bot.start()
  File "/home/guillaume/Applications/PokemonGo-Bot/pokemongo_bot/__init__.py", line 127, in start
    init_inventory(self)
  File "/home/guillaume/Applications/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1273, in init_inventory
    _inventory = Inventory(bot)
  File "/home/guillaume/Applications/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1111, in __init__
    self.refresh()
  File "/home/guillaume/Applications/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1121, in refresh
    self.update_web_inventory()
  File "/home/guillaume/Applications/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1148, in update_web_inventory
    self.bot.logger.info('[x] Error while opening inventory file for read: %s' % e, 'red')
NameError: global name 'e' is not defined
[2016-08-30 10:46:20] [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/home/guillaume/.local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/guillaume/.local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/guillaume/.local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/guillaume/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/guillaume/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/guillaume/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/guillaume/.local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/guillaume/.local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
[2016-08-30 10:46:20] [sentry.errors.uncaught] [ERROR] [u"NameError: global name 'e' is not defined", u'  File "pokecli.py", line 768, in <module>', u'  File "pokecli.py", line 119, in main', u'  File "pokecli.py", line 86, in start_bot', u'  File "pokemongo_bot/__init__.py", line 127, in start', u'  File "pokemongo_bot/inventory.py", line 1273, in init_inventory', u'  File "pokemongo_bot/inventory.py", line 1111, in __init__', u'  File "pokemongo_bot/inventory.py", line 1121, in refresh', u'  File "pokemongo_bot/inventory.py", line 1148, in update_web_inventory']
mardi 30 août 2016, 10:46:20 (UTC+0200) Pokebot  Stopped.`

**Comment by mjmadsen** [comment]
@castorfou Try PR #4924

**Comment by prusswan** [comment]
I have a similiar error  "UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 38: invalid start byte",  happens after 400, message bad request syntax

> 127.0.0.1 - - [06/Sep/2016 18:23:12] code 400, message Bad request syntax ("\x81\xfe\x00\x941\xb1\xb4\x1d\x05\x83\xef?S\xde\xc0'S\xc3\xdb|U\xd2\xd5nE\x93\x98=J\x93\xd5~R\xde\xc1sE\x93\x8e=\x13\xc1\xdbvT\xc2\xd7|_\xee\xc7z\x13\x9d\x94?U\xd0\xc0|\x13\x8b\x94f\x13\xdc\xc7z\x13\x8b\x94?u\xd8\xc7~P\xc3\xd0xU\x91\x87e\x11\xe1\xdbiX\xde\xda3\x13\x9d\x94?X\xc5\xd1p\x13\x8b\x94?a\xde\xc0t^\xdf\x961\x11\x93\xd5p^\xc4\xdai\x13\x8b\x94?\x02\x93\xc91\x11\x93\xd1kT\xdf\xc0?\x0b\x91\x96tE\xd4\xd9BU\xd8\xc7~P\xc3\xd0xU\x93\xc9@\x81\xfe\x013\x90\xc7\xf8\xa0\xa4\xf5\xa3\x82\xf2\xa8\x8c\x9a\xf2\xb5\x97\xc1\xf4\xa4\x99\xd3\xe4\xe5\xd4\x80\xeb\xe5\x99\xc3\xf3\xa8\x8d\xce\xe4\xe5\xc2\x80\xb2\xb7\x97\xcb\xf5\xb4\x9b\xc1\xfe\x98\x8b\xc7\xb2\xeb\xd8\x82\xf4\xa6\x8c\xc1\xb2\xfd\xd8\xdb\xb2\xb7\x97\xcb\xf5\xaa\x97\xce\xcf\xae\x9c\x82\xaa\xe7\xc9\x93\xbc\xe7\xda\xc5\xe8\xb7\x91\xd2\xf1\xb3\x91\xcf\xfe\x98\x8c\xc9\xfd\xa2\x8b\xd4\xf1\xaa\x88\xff\xfd\xb4\xda\x9a\xb0\xf6\xcc\x97\xa3\xf6\xcd\x97\xa5\xf3\xca\x98\xa1\xf5\xd4\x80\xb2\xab\x97\xce\xf7\xae\x8c\xd5\xf4\xa2\xda\x9a\xb0\xf6\xc8\x93\xbe\xff\xcb\x93\xa1\xf0\xcb\x99\xa6\xf0\xc1\x92\xa0\xf5\xca\x8c\xb0\xe5\x88\xcf\xfb\xa2\x95\xcf\xfe\x98\x96\xc1\xfd\xa2\xda\x9a\xb0\xe5\xaf\xc5\xf5\xa3\x94\xc5\xb2\xeb\xd8\x82\xfc\xa6\x8c\xc9\xe4\xb2\x9c\xc5\xb2\xfd\xd8\x91\xbe\xf4\xc8\x96\xa4\xf3\xcd\x97\xa2\xf3\xc1\x95\xa8\xf2\xc9\x93\xa5\xeb\xd8\x82\xe3\xb7\x99\xd7\xfe\x98\x88\xcf\xf9\xa9\x8c\xff\xf9\xa3\xda\x9a\xb0\xe5\xcb\x91\xf4\xa6\xc9\x99\xa8\xa3\xce\x91\xf6\xe5\xd4\x80\xb2\xa2\x96\xc3\xff\xb2\x96\xd4\xf5\xb5\xa7\xc9\xf4\xe5\xc2\x80\xa9\xf4\xc9\x92\xa3\xf2\xca\x92\xa2\xf2\xc0\x94\xa8\xf0\xcf\x98\xa2\xf6\x85\x8c\xb0\xe5\x9d\xd6\xf5\xa9\x8c\x82\xaa\xe7\xda\xc3\xf1\xb3\x9b\xc8\xf1\xa5\x94\xc5\xcf\xb7\x97\xcb\xf5\xaa\x97\xce\xb2\xba\xa5\x81\xfe\x013X\x99\x9d\xbdl\xab\xc6\x9f:\xf6\xe9\x87:\xeb\xf2\xdc<\xfa\xfc\xce,\xbb\xb1\x9d#\xbb\xfc\xde;\xf6\xe8\xd3,\xbb\xa7\x9dz\xe9\xf2\xd6=\xea\xfe\xdc6\xc6\xee\xdaz\xb5\xbd\x9f<\xf8\xe9\xdcz\xa3\xbd\xc6z\xe9\xf2\xd6=\xf4\xf2\xd3\x07\xf0\xf9\x9fb\xb9\xa9\x8bt\xb9\xbf\xd8 \xe9\xf4\xcf9\xed\xf4\xd26\xc6\xe9\xd45\xfc\xee\xc99\xf4\xed\xe25\xea\xbf\x87x\xa8\xa9\x8ak\xa8\xa8\x85h\xae\xa9\x8eh\xa1\xb1\x9dz\xf5\xf2\xd3?\xf0\xe9\xc8<\xfc\xbf\x87x\xa8\xad\x8ev\xa1\xae\x8eh\xa1\xae\x8ea\xab\xa8\x88h\xae\xa8\x91x\xbb\xed\xd23\xfc\xf0\xd26\xc6\xf3\xdc5\xfc\xbf\x87x\xbb\xcd\xdc*\xf8\xee\x9ft\xb9\xbf\xd19\xed\xf4\xc9-\xfd\xf8\x9fb\xb9\xac\x93k\xa9\xab\x85`\xac\xac\x8bh\xab\xa8\x8co\xac\xaf\x91x\xbb\xee\xcd9\xee\xf3\xe2(\xf6\xf4\xd3,\xc6\xf4\xd9z\xa3\xbd\x9fk\xa8\xf9\xdci\xa0\xa5\xd9m\xff\xac\x9ft\xb9\xbf\xd86\xfa\xf2\xc86\xed\xf8\xcf\x07\xf0\xf9\x9fb\xb9\xac\x8eh\xa1\xa8\x8am\xa8\xac\x85`\xa9\xae\x88j\xaa\xad\x89a\xaa\xe0\x91x\xbb\xf8\xcb=\xf7\xe9\x9fb\xb9\xbf\xde9\xed\xfe\xd59\xfb\xf1\xd8\x07\xe9\xf2\xd6=\xf4\xf2\xd3z\xe4\xc0\x81\xfe\x01S\x9alKH\xae^\x10j\xf8\x03?r\xf8\x1e$)\xfe\x0f*;\xeeNgh\xe1N*+\xf9\x03>&\xeeNqh\xb8\x1c$#\xff\x1f()\xf438/\xb8@kj\xfe\r?)\xb8Vk3\xb8")
Traceback (most recent call last):
  File "/home/prusswan/Projects/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "/home/prusswan/Projects/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 719, in process_request
    proto.__init__(sock, address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 342, in handle
    self.handle_one_request()
  File "/home/prusswan/Projects/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 351, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 365, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 396, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 433, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 469, in log_message
    format%args))
  File "/home/prusswan/Projects/PokemonGo-Bot/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
  File "/home/prusswan/Projects/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 38: invalid start byte

**Comment by belinux** [comment]
Same here.. Output in case it helps:
` 127.0.0.1 - - [06/Sep/2016 13:59:42] code 400, message Bad request syntax ('\x81\xfe\x00\xd4\x1c\x7fw\xd9(M,\xfb~\x10\x03\xe3~\r\x18\xb8x\x1c\x16\xaah][\xf9g]\x16\xba\x7f\x10\x02\xb7h]M\xf9>\x14\x16\xb7}\x12\x12\xef%IN\xfb0_U\xbd}\x0b\x16\xfb&_\x0c\xfbq\x0c\x10\xfb&_U\x9c{\x18\x04\xf9u\x11\x14\xac~\x1e\x03\xb0r\x18M\xf9GOY\xef+PB\xf7,_\x1c\xb4A__\x9c{\x18\x04\xf9p\x1a\x11\xad&_A\xf5<6\x19\xbai\x1d\x16\xadu\x11\x10\xe3<N^\xfb0_U\xbc{\x18\x04\xfb&_U\xe92I@\xf6)QG\xf9w\x12U\xf5<]\x12\xbe{\x0c(\xb5y\x19\x03\xfb&_A\xf5<]\x12\xbe{\x0c(\xb0r\x1cU\xe3<N')
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
     func(*args, **kwargs)
   File "/usr/lib/python2.7/site-packages/eventlet/wsgi.py", line 719, in process_request
     proto.__init__(sock, address, self)
   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
     self.handle()
   File "/usr/lib/python2.7/BaseHTTPServer.py", line 342, in handle
     self.handle_one_request()
   File "/usr/lib/python2.7/site-packages/eventlet/wsgi.py", line 351, in handle_one_request
     if not self.parse_request():
   File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
     self.send_error(400, "Bad request syntax (%r)" % requestline)
   File "/usr/lib/python2.7/BaseHTTPServer.py", line 365, in send_error
     self.send_response(code, message)
   File "/usr/lib/python2.7/BaseHTTPServer.py", line 396, in send_response
     self.log_request(code)
   File "/usr/lib/python2.7/BaseHTTPServer.py", line 433, in log_request
     self.requestline, str(code), str(size))
   File "/usr/lib/python2.7/BaseHTTPServer.py", line 469, in log_message
     format%args))
   File "/usr/lib/python2.7/codecs.py", line 369, in write
     data, consumed = self.encode(object, self.errors)
   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
     return codecs.utf_8_decode(input, errors, True)
 UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 38: invalid start byte
 [Errno 104] Connection reset by peer
`
