### ISSUE TITLE
[Feature Request] Logging in after 900 seconds might be a bot detection vector

### ISSUE THREAD

**Issue by tiagoAnon** [PokemonGoF/PokemonGo-Bot#5579]
### Short Description
Logging in into Pokemon go has been failing a lot lately (every time I open the app, I'm forced to tap "Try again" almost every time). This might be some tactic from Niantic to detect bots like this that will try to login again after exactly 900 seconds.

### Possible solution
This retry attempt should be more human, like:

1. Try again a few more times as soon as the server throws a bad response (wait 2 or 3 seconds between the first and the second request)
2. Try again at the speed of an app relauch
3. Wait a random amount of time (few minutes) and try again.

### How it would help others
It would avoid bot detection.

**Comment by PokemonGoZ** [comment]
This could be done by using a .bat file or script file to restart the bot at a random amount of time between two intervals. Currently, it takes my iPhone 6 6-10 seconds to relaunch the app and get past the Niantic screen. We could make the .bat or script file restart between 6-15 seconds (for the actual loading after the Niantic screen to get done). Currently on my mac this is my code.

`
cd PokemonGo-Bot
source bin/activate
until (python pokecli.py); do
    echo "Process crashed with exit code $?.  Respawning.." >&2
    sleep 5
done
`

Sleep could be a random number.

**Comment by Gobberwart** [comment]
You can configure this delay yourself in your config.json file.

`    "reconnecting_timeout": 15,`

15 = 15 minutes = 900 seconds

It doesn't achieve the randomness but at least it doesn't ALWAYS have to be 900.

**Comment by ultrafunkamsterdam** [comment]
You really think Niantic takes this specific bot's 900 seconds reconnect time as trigger to  flag and ban?
I'm using the bot in a different way (each of my account runs for 60/90/120 seconds), and there's always about 10% getting the 'try again in 900 seconds' message, but it shuts down after the amount of seconds that i specify, so it never reaches the reconnect time. Still having accounts banned and even the vps ip is banned.
